use MY_WEIBO_DATABASE;

DROP TABLE IF EXISTS `NAME`;
CREATE TABLE `NAME` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `LAST_VISIT` int(10) unsigned DEFAULT NULL,
  `LINK_ID` int(10) unsigned NOT NULL,
  `ADD_TIME` int(10) unsigned NOT NULL,
  `SEX` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `HOMETOWN` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `CONTENT_VISIT` tinyint(4) unsigned NOT NULL DEFAULT 0,
  `CONTENT_TOTAL` int(10) NOT NULL DEFAULT 0,
  `CONTENT_ZHUANGFA` int(10) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `LINK_ID` (`LINK_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS `CONTENT`;
CREATE TABLE `CONTENT` (
    `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
    `LINK_ID` int(10) unsigned DEFAULT NULL,
    `CONTENT` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `LINK_ID` (`LINK_ID`)
)ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 COLLATE=utf8_unicode_ci;
